# Generated by Django 4.0.5 on 2022-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0004_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='item_title'),
        ),
    ]
