# Generated by Django 4.0.5 on 2022-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_item_discout_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the dummy description of this product item'),
        ),
    ]
