# Generated by Django 4.0.5 on 2022-06-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0010_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discout',
            new_name='discount',
        ),
    ]
