# Generated by Django 4.0.5 on 2022-06-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0015_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amouny',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='useer',
            new_name='user',
        ),
    ]
